[package]

name = "cassandra"
version = "0.0.1"
authors = ["Luke Steensen <luke.steensen@gmail.com>"]

[dependencies]
uuid = "*"
byteorder = { git = "https://github.com/lukesteensen/byteorder", branch = "read_exact" }
